language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ksavon/docker-react:test -f Dockerfile.dev .

script:
  - docker run -e CI=true ksavon/docker-react:test npm run test

after_success:
  - docker build -t kswest.azurecr.io/ksavon/docker-react:latest .
  - echo "Image is built"
  - docker login kswest.azurecr.io --username $SP_APP_ID --password $SP_PASSWD
  - echo "Azure registry loged in"
  - docker push kswest.azurecr.io/ksavon/docker-react:latest
  - echo "Image Pushed"
