language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ksavon/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ksavon/docker-react npm run test

deploy:
  verbose: true
  provider: azure_web_apps
  site: https://react-app-ksavon-staging.azurewebsites.net
  slot: react-app-ksavon-staging
